//
// Copyright (c) 2009-2013 Marat Abrarov (abrarov@mail.ru)
//

#ifndef MA_CHRONO_BUILD_ENVIRONMENT
#define MA_CHRONO_BUILD_ENVIRONMENT

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif // defined(_MSC_VER) && (_MSC_VER >= 1200)

#define MA_CHRONO_BUILD_ENVIRONMENT_WINDOWS_VERSION_BIT 64
#define MA_CHRONO_BUILD_ENVIRONMENT_OFFICE_VERSION      2013
#define MA_CHRONO_BUILD_ENVIRONMENT_OFFICE_VERSION_BIT  64
//#define MA_CHRONO_BUILD_ENVIRONMENT_OFFICE_VERSION      2007
//#define MA_CHRONO_BUILD_ENVIRONMENT_DEMO
//#define MA_CHRONO_BUILD_ENVIRONMENT_DEMO_MAX_ROWS 10

#endif // MA_CHRONO_BUILD_ENVIRONMENT